In [2]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
Nsec = 16
DirectionalResults_list={}

for i in range(Nsec):
    DirectionalResults_list[i] = pd.read_csv('DirectionalResults/Hebi_Multi-Masts_'+str(math.floor(360/16*i)).zfill(3)+str(1)+'.txt',sep='\s+')
    # print(DirectionalResults_list[i])
DirectionalResults_list[Nsec] = pd.read_csv('DirectionalResults/Hebi_Multi-Masts_'+str(math.floor(360/16*0)).zfill(3)+str(1)+'.txt',sep='\s+')

<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
<>:5: SyntaxWarning: invalid escape sequence '\s'
<>:7: SyntaxWarning: invalid escape sequence '\s'
C:\Users\DELL\AppData\Local\Temp\ipykernel_6824\2865476708.py:5: SyntaxWarning: invalid escape sequence '\s'
  DirectionalResults_list[i] = pd.read_csv('DirectionalResults/Hebi_Multi-Masts_'+str(math.floor(360/16*i)).zfill(3)+str(1)+'.txt',sep='\s+')
C:\Users\DELL\AppData\Local\Temp\ipykernel_6824\2865476708.py:7: SyntaxWarning: invalid escape sequence '\s'
  DirectionalResults_list[Nsec] = pd.read_csv('DirectionalResults/Hebi_Multi-Masts_'+str(math.floor(360/16*0)).zfill(3)+str(1)+'.txt',sep='\s+')

In [4]:
DirectionalResults_list[0]

,Label,X (m),Y (m),Z (m),H (m),Vh,TI,D (°),I (°)
0,Mast1,38506757.8,3957473.3,701.6,80.0,1.306,0.259,1.1,3.5
1,T1,38504110.7,3957588.0,838.1,80.0,1.554,0.219,-8.6,3.3
2,T2,38504685.4,3957779.3,839.8,80.0,1.307,0.285,-10.6,2.0
3,T3,38509242.9,3957449.7,652.1,80.0,1.266,0.286,10.5,3.1
4,T4,38505205.1,3958447.5,808.1,80.0,1.276,0.282,-7.1,1.2
5,T5,38505609.2,3957934.2,780.1,80.0,1.059,0.346,3.3,0.6
6,T6,38505663.4,3958913.2,782.3,80.0,1.081,0.314,-6.8,6.7
7,T7,38506017.6,3957602.3,746.6,80.0,1.144,0.346,8.3,-0.4
8,T8,38506243.5,3958434.1,774.4,80.0,1.297,0.267,2.2,-0.1
9,T9,38506343.6,3957524.6,766.6,80.0,1.327,0.281,3.9,3.0
10,T10,38510343.2,3956924.3,610.6,80.0,1.414,0.252,9.1,1.5
11,T11,38507131.2,3957607.2,689.2,80.0,1.377,0.232,-1.9,0.6
12,T12,38507382.1,3957802.8,675.5,80.0,1.342,0.224,1.5,4.1
13,T13,38507943.3,3957720.1,677.9,80.0,1.513,0.198,0.6,0.5
14,T14,38508237.5,3957880.8,677.5,80.0,1.486,0.191,-1.7,3.9
15,T15,38508582.3,3957766.2,643.1,80.0,1.346,0.247,8.6,2.0
16,T16,38508909.9,3958865.5,670.0,80.0,1.367,0.226,-1.8,2.0
17,T17,38508943.8,3957609.6,667.7,80.0,1.378,0.265,8.5,1.1
18,T18,38509040.4,3957060.4,655.0,80.0,1.250,0.295,3.1,-1.9
19,T19,38509460.8,3957272.4,670.0,80.0,1.332,0.267,5.7,1.3
20,T20,38509775.0,3957373.4,660.0,80.0,1.297,0.265,2.5,5.7
21,T21,38510027.6,3957051.9,611.0,80.0,1.304,0.277,14.2,2.9
22,T22,38510589.4,3956966.2,640.0,80.0,1.462,0.205,7.0,5.4
23,T23,38510809.9,3956628.5,645.0,80.0,1.497,0.193,7.9,0.8
24,T24,38511111.5,3956496.2,640.0,80.0,1.565,0.183,2.7,2.1
25,Point1,38510492.0,3958862.0,3345.4,3000.0,1.902,0.051,0.0,0.8
26,VerticalProfile1#20,38506941.0,3958485.0,403.2,20.0,0.711,0.263,14.4,2.9
27,VerticalProfile1#40,38506941.0,3958485.0,423.2,40.0,0.756,0.295,12.7,3.5
28,VerticalProfile1#60,38506941.0,3958485.0,443.2,60.0,0.793,0.318,11.0,3.9
29,VerticalProfile1#80,38506941.0,3958485.0,463.2,80.0,0.830,0.333,9.5,4.0
30,VerticalProfile1#100,38506941.0,3958485.0,483.2,100.0,0.866,0.342,8.3,4.0
31,VerticalProfile1#120,38506941.0,3958485.0,503.2,120.0,0.902,0.345,7.2,3.9
32,VerticalProfile1#140,38506941.0,3958485.0,523.2,140.0,0.938,0.346,6.1,3.8
33,VerticalProfile1#160,38506941.0,3958485.0,543.2,160.0,0.973,0.343,5.2,3.6
34,VerticalProfile1#180,38506941.0,3958485.0,563.2,180.0,1.007,0.336,4.3,3.4
35,VerticalProfile1#200,38506941.0,3958485.0,583.2,200.0,1.042,0.328,3.5,3.3
36,VerticalProfile2#20,38505650.0,3956406.0,420.1,20.0,0.143,1.000,22.5,4.9
37,VerticalProfile2#40,38505650.0,3956406.0,440.1,40.0,0.235,1.000,16.7,-0.7
38,VerticalProfile2#60,38505650.0,3956406.0,460.1,60.0,0.304,0.978,12.0,-3.5
39,VerticalProfile2#80,38505650.0,3956406.0,480.1,80.0,0.365,0.868,8.7,-4.6
40,VerticalProfile2#100,38505650.0,3956406.0,500.1,100.0,0.422,0.783,6.6,-4.9
41,VerticalProfile2#120,38505650.0,3956406.0,520.1,120.0,0.477,0.714,5.2,-5.0
42,VerticalProfile2#140,38505650.0,3956406.0,540.1,140.0,0.529,0.661,4.2,-4.9
43,VerticalProfile2#160,38505650.0,3956406.0,560.1,160.0,0.579,0.617,3.4,-4.7
44,VerticalProfile2#180,38505650.0,3956406.0,580.1,180.0,0.627,0.578,2.8,-4.4
45,VerticalProfile2#200,38505650.0,3956406.0,600.1,200.0,0.674,0.544,2.3,-4.2

In [5]:
DirectionalResults_list[Nsec]

,Label,X (m),Y (m),Z (m),H (m),Vh,TI,D (°),I (°)
0,Mast1,38506757.8,3957473.3,701.6,80.0,1.306,0.259,1.1,3.5
1,T1,38504110.7,3957588.0,838.1,80.0,1.554,0.219,-8.6,3.3
2,T2,38504685.4,3957779.3,839.8,80.0,1.307,0.285,-10.6,2.0
3,T3,38509242.9,3957449.7,652.1,80.0,1.266,0.286,10.5,3.1
4,T4,38505205.1,3958447.5,808.1,80.0,1.276,0.282,-7.1,1.2
5,T5,38505609.2,3957934.2,780.1,80.0,1.059,0.346,3.3,0.6
6,T6,38505663.4,3958913.2,782.3,80.0,1.081,0.314,-6.8,6.7
7,T7,38506017.6,3957602.3,746.6,80.0,1.144,0.346,8.3,-0.4
8,T8,38506243.5,3958434.1,774.4,80.0,1.297,0.267,2.2,-0.1
9,T9,38506343.6,3957524.6,766.6,80.0,1.327,0.281,3.9,3.0
10,T10,38510343.2,3956924.3,610.6,80.0,1.414,0.252,9.1,1.5
11,T11,38507131.2,3957607.2,689.2,80.0,1.377,0.232,-1.9,0.6
12,T12,38507382.1,3957802.8,675.5,80.0,1.342,0.224,1.5,4.1
13,T13,38507943.3,3957720.1,677.9,80.0,1.513,0.198,0.6,0.5
14,T14,38508237.5,3957880.8,677.5,80.0,1.486,0.191,-1.7,3.9
15,T15,38508582.3,3957766.2,643.1,80.0,1.346,0.247,8.6,2.0
16,T16,38508909.9,3958865.5,670.0,80.0,1.367,0.226,-1.8,2.0
17,T17,38508943.8,3957609.6,667.7,80.0,1.378,0.265,8.5,1.1
18,T18,38509040.4,3957060.4,655.0,80.0,1.250,0.295,3.1,-1.9
19,T19,38509460.8,3957272.4,670.0,80.0,1.332,0.267,5.7,1.3
20,T20,38509775.0,3957373.4,660.0,80.0,1.297,0.265,2.5,5.7
21,T21,38510027.6,3957051.9,611.0,80.0,1.304,0.277,14.2,2.9
22,T22,38510589.4,3956966.2,640.0,80.0,1.462,0.205,7.0,5.4
23,T23,38510809.9,3956628.5,645.0,80.0,1.497,0.193,7.9,0.8
24,T24,38511111.5,3956496.2,640.0,80.0,1.565,0.183,2.7,2.1
25,Point1,38510492.0,3958862.0,3345.4,3000.0,1.902,0.051,0.0,0.8
26,VerticalProfile1#20,38506941.0,3958485.0,403.2,20.0,0.711,0.263,14.4,2.9
27,VerticalProfile1#40,38506941.0,3958485.0,423.2,40.0,0.756,0.295,12.7,3.5
28,VerticalProfile1#60,38506941.0,3958485.0,443.2,60.0,0.793,0.318,11.0,3.9
29,VerticalProfile1#80,38506941.0,3958485.0,463.2,80.0,0.830,0.333,9.5,4.0
30,VerticalProfile1#100,38506941.0,3958485.0,483.2,100.0,0.866,0.342,8.3,4.0
31,VerticalProfile1#120,38506941.0,3958485.0,503.2,120.0,0.902,0.345,7.2,3.9
32,VerticalProfile1#140,38506941.0,3958485.0,523.2,140.0,0.938,0.346,6.1,3.8
33,VerticalProfile1#160,38506941.0,3958485.0,543.2,160.0,0.973,0.343,5.2,3.6
34,VerticalProfile1#180,38506941.0,3958485.0,563.2,180.0,1.007,0.336,4.3,3.4
35,VerticalProfile1#200,38506941.0,3958485.0,583.2,200.0,1.042,0.328,3.5,3.3
36,VerticalProfile2#20,38505650.0,3956406.0,420.1,20.0,0.143,1.000,22.5,4.9
37,VerticalProfile2#40,38505650.0,3956406.0,440.1,40.0,0.235,1.000,16.7,-0.7
38,VerticalProfile2#60,38505650.0,3956406.0,460.1,60.0,0.304,0.978,12.0,-3.5
39,VerticalProfile2#80,38505650.0,3956406.0,480.1,80.0,0.365,0.868,8.7,-4.6
40,VerticalProfile2#100,38505650.0,3956406.0,500.1,100.0,0.422,0.783,6.6,-4.9
41,VerticalProfile2#120,38505650.0,3956406.0,520.1,120.0,0.477,0.714,5.2,-5.0
42,VerticalProfile2#140,38505650.0,3956406.0,540.1,140.0,0.529,0.661,4.2,-4.9
43,VerticalProfile2#160,38505650.0,3956406.0,560.1,160.0,0.579,0.617,3.4,-4.7
44,VerticalProfile2#180,38505650.0,3956406.0,580.1,180.0,0.627,0.578,2.8,-4.4
45,VerticalProfile2#200,38505650.0,3956406.0,600.1,200.0,0.674,0.544,2.3,-4.2

In [6]:
mastdata = pd.read_csv('M9564(20210101-20211231)_1.txt',sep='\t')
mastdata

              Date/Time  Speed 80 m A  Speed 80 m A SD  Direction 80
0      2021/01/01 00:00           0.9              0.5           355
1      2021/01/01 00:10           0.4              0.2           355
2      2021/01/01 00:20           0.3              0.0           355
3      2021/01/01 00:30           0.3              0.0           355
4      2021/01/01 00:40           0.7              0.5           355
...                 ...           ...              ...           ...
52437  2021/12/31 23:10          10.6              0.9            14
52438  2021/12/31 23:20          11.4              1.2            14
52439  2021/12/31 23:30          11.8              0.9            14
52440  2021/12/31 23:40          10.0              0.8            13
52441  2021/12/31 23:50          10.5              0.9            13

[52442 rows x 4 columns]

In [7]:
mastdata['Direction 80']/(360/Nsec)

0        15.777778
1        15.777778
2        15.777778
3        15.777778
4        15.777778
           ...
52437     0.622222
52438     0.622222
52439     0.622222
52440     0.577778
52441     0.577778
Name: Direction 80, Length: 52442, dtype: float64

In [8]:
mastdata['Neib01'] = ((mastdata['Direction 80']/(360/Nsec)).astype(float)).apply(math.floor)
mastdata['Neib02'] = mastdata['Neib01']+1
mastdata['theta01'] = mastdata['Neib01']*360/Nsec
mastdata['theta02'] = mastdata['Neib02']*360/Nsec
# mastdata['Dev01'] = DirectionalResults_list[15]['D\xa0(°)'][0]

In [9]:
len(mastdata)

52442

In [10]:
# for i in range(Nsec+1):
Y01 = [DirectionalResults_list[mastdata['Neib01'][j]]['D\xa0(°)'][0] for j in range(len(mastdata))]
mastdata['Dev01'] = pd.DataFrame(Y01)
Y02 = [DirectionalResults_list[mastdata['Neib02'][j]]['D\xa0(°)'][0] for j in range(len(mastdata))]
mastdata['Dev02'] = pd.DataFrame(Y02)

In [80]:
# DirectionalResults_list[16]['D\xa0(°)'][0:25]

In [12]:
mastdata

,Date/Time,Speed 80 m A,Speed 80 m A SD,Direction 80,Neib01,Neib02,theta01,theta02,Dev01,Dev02
0,2021/01/01 00:00,0.9,0.5,355,15,16,337.5,360.0,6.2,1.1
1,2021/01/01 00:10,0.4,0.2,355,15,16,337.5,360.0,6.2,1.1
2,2021/01/01 00:20,0.3,0.0,355,15,16,337.5,360.0,6.2,1.1
3,2021/01/01 00:30,0.3,0.0,355,15,16,337.5,360.0,6.2,1.1
4,2021/01/01 00:40,0.7,0.5,355,15,16,337.5,360.0,6.2,1.1
...,...,...,...,...,...,...,...,...,...,...
52437,2021/12/31 23:10,10.6,0.9,14,0,1,0.0,22.5,1.1,-5.7
52438,2021/12/31 23:20,11.4,1.2,14,0,1,0.0,22.5,1.1,-5.7
52439,2021/12/31 23:30,11.8,0.9,14,0,1,0.0,22.5,1.1,-5.7
52440,2021/12/31 23:40,10.0,0.8,13,0,1,0.0,22.5,1.1,-5.7
52441,2021/12/31 23:50,10.5,0.9,13,0,1,0.0,22.5,1.1,-5.7

In [13]:
mastdata['lambda01'] = (mastdata['theta02']-mastdata['Direction 80'])/(360/Nsec)
mastdata['lambda02'] = (mastdata['Direction 80']-mastdata['theta01'])/(360/Nsec)
mastdata

,Date/Time,Speed 80 m A,Speed 80 m A SD,Direction 80,Neib01,Neib02,theta01,theta02,Dev01,Dev02,lambda01,lambda02
0,2021/01/01 00:00,0.9,0.5,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
1,2021/01/01 00:10,0.4,0.2,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
2,2021/01/01 00:20,0.3,0.0,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
3,2021/01/01 00:30,0.3,0.0,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
4,2021/01/01 00:40,0.7,0.5,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
...,...,...,...,...,...,...,...,...,...,...,...,...
52437,2021/12/31 23:10,10.6,0.9,14,0,1,0.0,22.5,1.1,-5.7,0.377778,0.622222
52438,2021/12/31 23:20,11.4,1.2,14,0,1,0.0,22.5,1.1,-5.7,0.377778,0.622222
52439,2021/12/31 23:30,11.8,0.9,14,0,1,0.0,22.5,1.1,-5.7,0.377778,0.622222
52440,2021/12/31 23:40,10.0,0.8,13,0,1,0.0,22.5,1.1,-5.7,0.422222,0.577778
52441,2021/12/31 23:50,10.5,0.9,13,0,1,0.0,22.5,1.1,-5.7,0.422222,0.577778

In [14]:
Turbinedata = pd.DataFrame()
Turbinedata_S1 = pd.DataFrame([DirectionalResults_list[mastdata['Neib01'][k]]['Vh'][1:25] for k in range(len(mastdata))])
Turbinedata_S2 = pd.DataFrame([DirectionalResults_list[mastdata['Neib02'][k]]['Vh'][1:25] for k in range(len(mastdata))])
Mastdata_S1 = pd.DataFrame([DirectionalResults_list[mastdata['Neib01'][k]]['Vh'][0] for k in range(len(mastdata))])
Mastdata_S2 = pd.DataFrame([DirectionalResults_list[mastdata['Neib02'][k]]['Vh'][0] for k in range(len(mastdata))])

In [15]:
# DirectionalResults_list[mastdata['Neib01'][1]]['D\xa0(°)']

In [16]:
Turbinedata_Dev1 = pd.DataFrame([DirectionalResults_list[mastdata['Neib01'][k]]['D\xa0(°)'][1:25] for k in range(len(mastdata))])
Turbinedata_Dev2 = pd.DataFrame([DirectionalResults_list[mastdata['Neib02'][k]]['D\xa0(°)'][1:25] for k in range(len(mastdata))])

In [17]:

# Turbinedata_V = (mastdata['lambda01']*Turbinedata_S1+mastdata['lambda02']*Turbinedata_S2)/(mastdata['lambda01']*Mastdata_S1+mastdata['lambda02']*Mastdata_S2)*mastdata['Speed 80 m A']

# 重置索引
Turbinedata_S1_reset = Turbinedata_S1.reset_index(drop=True)
lambda_col_reset1 = mastdata['lambda01'].reset_index(drop=True)

Turbinedata_S2_reset = Turbinedata_S2.reset_index(drop=True)
lambda_col_reset2 = mastdata['lambda02'].reset_index(drop=True)

# 广播相乘
Turbinedata_V1 = Turbinedata_S1_reset.mul(lambda_col_reset1, axis=0) + Turbinedata_S2_reset.mul(lambda_col_reset2, axis=0)

Turbinedata_V2 = Mastdata_S1.multiply(pd.DataFrame(mastdata['lambda01'])['lambda01'],axis=0)+Mastdata_S2.multiply(pd.DataFrame(mastdata['lambda02'])['lambda02'],axis=0)

Turbinedata_V = Turbinedata_V1.div(Turbinedata_V2.iloc[:, 0], axis=0).multiply(mastdata['Speed 80 m A'],axis=0)

In [18]:
Turbinedata_Dev1

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
D (°),2.9,-6.6,12.3,-0.3,1.4,-9.6,6.1,1.8,6.0,16.5,...,13.0,-2.2,12.1,5.4,8.7,4.6,18.9,11.0,11.6,9.3
D (°),2.9,-6.6,12.3,-0.3,1.4,-9.6,6.1,1.8,6.0,16.5,...,13.0,-2.2,12.1,5.4,8.7,4.6,18.9,11.0,11.6,9.3
D (°),2.9,-6.6,12.3,-0.3,1.4,-9.6,6.1,1.8,6.0,16.5,...,13.0,-2.2,12.1,5.4,8.7,4.6,18.9,11.0,11.6,9.3
D (°),2.9,-6.6,12.3,-0.3,1.4,-9.6,6.1,1.8,6.0,16.5,...,13.0,-2.2,12.1,5.4,8.7,4.6,18.9,11.0,11.6,9.3
D (°),2.9,-6.6,12.3,-0.3,1.4,-9.6,6.1,1.8,6.0,16.5,...,13.0,-2.2,12.1,5.4,8.7,4.6,18.9,11.0,11.6,9.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
D (°),-8.6,-10.6,10.5,-7.1,3.3,-6.8,8.3,2.2,3.9,9.1,...,8.6,-1.8,8.5,3.1,5.7,2.5,14.2,7.0,7.9,2.7
D (°),-8.6,-10.6,10.5,-7.1,3.3,-6.8,8.3,2.2,3.9,9.1,...,8.6,-1.8,8.5,3.1,5.7,2.5,14.2,7.0,7.9,2.7
D (°),-8.6,-10.6,10.5,-7.1,3.3,-6.8,8.3,2.2,3.9,9.1,...,8.6,-1.8,8.5,3.1,5.7,2.5,14.2,7.0,7.9,2.7
D (°),-8.6,-10.6,10.5,-7.1,3.3,-6.8,8.3,2.2,3.9,9.1,...,8.6,-1.8,8.5,3.1,5.7,2.5,14.2,7.0,7.9,2.7
D (°),-8.6,-10.6,10.5,-7.1,3.3,-6.8,8.3,2.2,3.9,9.1,...,8.6,-1.8,8.5,3.1,5.7,2.5,14.2,7.0,7.9,2.7

In [19]:
Turbinedata_D1 = (Turbinedata_Dev1 + (mastdata['theta01'].to_numpy())[:,np.newaxis])
Turbinedata_D1_reset = Turbinedata_D1.reset_index(drop=True)
# theta_col_reset1 = mastdata['theta01'].reset_index(drop=True)

Turbinedata_D2 = (Turbinedata_Dev2 + (mastdata['theta02'].to_numpy())[:,np.newaxis])
Turbinedata_D2_reset = Turbinedata_D2.reset_index(drop=True)
# theta_col_reset2 = mastdata['theta02'].reset_index(drop=True)

Turbinedata_Dir = Turbinedata_D1_reset.mul(lambda_col_reset1, axis=0) + Turbinedata_D2_reset.mul(lambda_col_reset2, axis=0)
Turbinedata_Dir

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,348.955556,345.288889,365.900000,349.411111,357.877778,347.577778,362.811111,357.111111,359.366667,365.744444,...,364.577778,353.111111,364.300000,358.611111,361.366667,357.966667,370.244444,362.888889,363.722222,359.166667
1,348.955556,345.288889,365.900000,349.411111,357.877778,347.577778,362.811111,357.111111,359.366667,365.744444,...,364.577778,353.111111,364.300000,358.611111,361.366667,357.966667,370.244444,362.888889,363.722222,359.166667
2,348.955556,345.288889,365.900000,349.411111,357.877778,347.577778,362.811111,357.111111,359.366667,365.744444,...,364.577778,353.111111,364.300000,358.611111,361.366667,357.966667,370.244444,362.888889,363.722222,359.166667
3,348.955556,345.288889,365.900000,349.411111,357.877778,347.577778,362.811111,357.111111,359.366667,365.744444,...,364.577778,353.111111,364.300000,358.611111,361.366667,357.966667,370.244444,362.888889,363.722222,359.166667
4,348.955556,345.288889,365.900000,349.411111,357.877778,347.577778,362.811111,357.111111,359.366667,365.744444,...,364.577778,353.111111,364.300000,358.611111,361.366667,357.966667,370.244444,362.888889,363.722222,359.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,2.102222,5.764444,20.455556,8.268889,17.486667,12.053333,19.313333,15.142222,14.228889,15.944444,...,18.742222,12.946667,19.264444,14.922222,15.655556,13.637778,21.417778,16.706667,17.482222,11.597778
52438,2.102222,5.764444,20.455556,8.268889,17.486667,12.053333,19.313333,15.142222,14.228889,15.944444,...,18.742222,12.946667,19.264444,14.922222,15.655556,13.637778,21.417778,16.706667,17.482222,11.597778
52439,2.102222,5.764444,20.455556,8.268889,17.486667,12.053333,19.313333,15.142222,14.228889,15.944444,...,18.742222,12.946667,19.264444,14.922222,15.655556,13.637778,21.417778,16.706667,17.482222,11.597778
52440,1.337778,4.595556,19.744444,7.171111,16.473333,10.706667,18.526667,14.217778,13.491111,15.455556,...,18.017778,11.893333,18.495556,14.077778,14.944444,12.842222,20.902222,16.013333,16.797778,10.962222
52441,1.337778,4.595556,19.744444,7.171111,16.473333,10.706667,18.526667,14.217778,13.491111,15.455556,...,18.017778,11.893333,18.495556,14.077778,14.944444,12.842222,20.902222,16.013333,16.797778,10.962222

In [20]:
mastdata

,Date/Time,Speed 80 m A,Speed 80 m A SD,Direction 80,Neib01,Neib02,theta01,theta02,Dev01,Dev02,lambda01,lambda02
0,2021/01/01 00:00,0.9,0.5,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
1,2021/01/01 00:10,0.4,0.2,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
2,2021/01/01 00:20,0.3,0.0,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
3,2021/01/01 00:30,0.3,0.0,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
4,2021/01/01 00:40,0.7,0.5,355,15,16,337.5,360.0,6.2,1.1,0.222222,0.777778
...,...,...,...,...,...,...,...,...,...,...,...,...
52437,2021/12/31 23:10,10.6,0.9,14,0,1,0.0,22.5,1.1,-5.7,0.377778,0.622222
52438,2021/12/31 23:20,11.4,1.2,14,0,1,0.0,22.5,1.1,-5.7,0.377778,0.622222
52439,2021/12/31 23:30,11.8,0.9,14,0,1,0.0,22.5,1.1,-5.7,0.377778,0.622222
52440,2021/12/31 23:40,10.0,0.8,13,0,1,0.0,22.5,1.1,-5.7,0.422222,0.577778
52441,2021/12/31 23:50,10.5,0.9,13,0,1,0.0,22.5,1.1,-5.7,0.422222,0.577778

In [21]:
TI_mes = mastdata['Speed 80 m A SD']/mastdata['Speed 80 m A']
TI_mes

0        0.555556
1        0.500000
2        0.000000
3        0.000000
4        0.714286
           ...
52437    0.084906
52438    0.105263
52439    0.076271
52440    0.080000
52441    0.085714
Length: 52442, dtype: float64

In [22]:
mastdata['Neib01']

0        15
1        15
2        15
3        15
4        15
         ..
52437     0
52438     0
52439     0
52440     0
52441     0
Name: Neib01, Length: 52442, dtype: int64

In [23]:
# [DirectionalResults_list[mastdata['Neib01'][k]]['TI'][0] for k in range(len(mastdata))]

# len([DirectionalResults_list[mastdata['Neib01'][k]]['TI'][0] for k in range(len(mastdata))])

In [24]:
TI_cal_mast_1 = pd.DataFrame([DirectionalResults_list[mastdata['Neib01'][k]]['TI'][0] for k in range(len(mastdata))])
TI_cal_mast_2 = pd.DataFrame([DirectionalResults_list[mastdata['Neib02'][k]]['TI'][0] for k in range(len(mastdata))])

In [25]:
TI_cal_respoint_1 = pd.DataFrame([DirectionalResults_list[mastdata['Neib01'][k]]['TI'][1:25] for k in range(len(mastdata))])
TI_cal_respoint_2 = pd.DataFrame([DirectionalResults_list[mastdata['Neib02'][k]]['TI'][1:25] for k in range(len(mastdata))])
TI_cal_respoint_1

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
TI,0.217,0.235,0.327,0.184,0.292,0.250,0.344,0.287,0.321,0.371,...,0.298,0.240,0.292,0.291,0.288,0.304,0.412,0.309,0.289,0.266
TI,0.217,0.235,0.327,0.184,0.292,0.250,0.344,0.287,0.321,0.371,...,0.298,0.240,0.292,0.291,0.288,0.304,0.412,0.309,0.289,0.266
TI,0.217,0.235,0.327,0.184,0.292,0.250,0.344,0.287,0.321,0.371,...,0.298,0.240,0.292,0.291,0.288,0.304,0.412,0.309,0.289,0.266
TI,0.217,0.235,0.327,0.184,0.292,0.250,0.344,0.287,0.321,0.371,...,0.298,0.240,0.292,0.291,0.288,0.304,0.412,0.309,0.289,0.266
TI,0.217,0.235,0.327,0.184,0.292,0.250,0.344,0.287,0.321,0.371,...,0.298,0.240,0.292,0.291,0.288,0.304,0.412,0.309,0.289,0.266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TI,0.219,0.285,0.286,0.282,0.346,0.314,0.346,0.267,0.281,0.252,...,0.247,0.226,0.265,0.295,0.267,0.265,0.277,0.205,0.193,0.183
TI,0.219,0.285,0.286,0.282,0.346,0.314,0.346,0.267,0.281,0.252,...,0.247,0.226,0.265,0.295,0.267,0.265,0.277,0.205,0.193,0.183
TI,0.219,0.285,0.286,0.282,0.346,0.314,0.346,0.267,0.281,0.252,...,0.247,0.226,0.265,0.295,0.267,0.265,0.277,0.205,0.193,0.183
TI,0.219,0.285,0.286,0.282,0.346,0.314,0.346,0.267,0.281,0.252,...,0.247,0.226,0.265,0.295,0.267,0.265,0.277,0.205,0.193,0.183
TI,0.219,0.285,0.286,0.282,0.346,0.314,0.346,0.267,0.281,0.252,...,0.247,0.226,0.265,0.295,0.267,0.265,0.277,0.205,0.193,0.183

In [26]:
TI_cal_mast_1

           0
0      0.345
1      0.345
2      0.345
3      0.345
4      0.345
...      ...
52437  0.259
52438  0.259
52439  0.259
52440  0.259
52441  0.259

[52442 rows x 1 columns]

In [27]:
TI_cal_mast_2

           0
0      0.259
1      0.259
2      0.259
3      0.259
4      0.259
...      ...
52437  0.197
52438  0.197
52439  0.197
52440  0.197
52441  0.197

[52442 rows x 1 columns]

In [28]:
TI_cal_mast_dir = TI_cal_mast_1.multiply(pd.DataFrame(mastdata['lambda01'])['lambda01'],axis=0) + TI_cal_mast_2.multiply(pd.DataFrame(mastdata['lambda02'])['lambda02'],axis=0)
TI_cal_mast_dir

              0
0      0.278111
1      0.278111
2      0.278111
3      0.278111
4      0.278111
...         ...
52437  0.220422
52438  0.220422
52439  0.220422
52440  0.223178
52441  0.223178

[52442 rows x 1 columns]

In [29]:
TI_cal_respoint_1_reset = TI_cal_respoint_1.reset_index(drop=True)
TI_cal_respoint_2_reset = TI_cal_respoint_2.reset_index(drop=True)

TI_cal_respoint_dir = TI_cal_respoint_1_reset.mul(lambda_col_reset1, axis=0) + TI_cal_respoint_2_reset.mul(lambda_col_reset2, axis=0)
TI_cal_respoint_dir

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
1,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
2,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
3,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
4,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52438,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52439,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52440,0.289489,0.299444,0.237467,0.299911,0.324622,0.328444,0.290533,0.235222,0.228422,0.205778,...,0.262600,0.249111,0.247089,0.258022,0.228289,0.217044,0.242333,0.172067,0.180289,0.191089
52441,0.289489,0.299444,0.237467,0.299911,0.324622,0.328444,0.290533,0.235222,0.228422,0.205778,...,0.262600,0.249111,0.247089,0.258022,0.228289,0.217044,0.242333,0.172067,0.180289,0.191089

In [30]:
Delta_TI_mast_dir = pd.DataFrame(TI_mes) - TI_cal_mast_dir
Delta_TI_mast_dir

              0
0      0.277444
1      0.221889
2     -0.278111
3     -0.278111
4      0.436175
...         ...
52437 -0.135517
52438 -0.115159
52439 -0.144151
52440 -0.143178
52441 -0.137463

[52442 rows x 1 columns]

In [31]:
Turbinedata_V = Turbinedata_V1.div(Turbinedata_V2.iloc[:, 0], axis=0).multiply(mastdata['Speed 80 m A'],axis=0)
Turbinedata_V

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,1.097646,0.952890,0.869642,0.957396,0.780701,0.819123,0.816356,0.918104,0.932335,0.946012,...,0.921346,0.964433,0.946486,0.878022,0.927196,0.903716,0.868693,0.988387,1.011393,1.061832
1,0.487843,0.423507,0.386507,0.425509,0.346978,0.364055,0.362825,0.408046,0.414371,0.420450,...,0.409487,0.428637,0.420661,0.390232,0.412087,0.401651,0.386086,0.439283,0.449508,0.471926
2,0.365882,0.317630,0.289881,0.319132,0.260234,0.273041,0.272119,0.306035,0.310778,0.315337,...,0.307115,0.321478,0.315495,0.292674,0.309065,0.301239,0.289564,0.329462,0.337131,0.353944
3,0.365882,0.317630,0.289881,0.319132,0.260234,0.273041,0.272119,0.306035,0.310778,0.315337,...,0.307115,0.321478,0.315495,0.292674,0.309065,0.301239,0.289564,0.329462,0.337131,0.353944
4,0.853725,0.741137,0.676388,0.744642,0.607212,0.637096,0.634944,0.714081,0.725149,0.735787,...,0.716602,0.750114,0.736156,0.682906,0.721152,0.702890,0.675650,0.768746,0.786639,0.825870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,9.778951,9.143664,10.890494,9.139798,8.933863,8.328331,9.911086,10.659007,11.097773,11.633540,...,10.050617,9.814086,10.909322,10.096343,11.126184,10.710784,10.876709,11.831909,11.875450,11.815602
52438,10.516985,9.833752,11.712418,9.829594,9.608117,8.956885,10.659092,11.463460,11.935341,12.511542,...,10.809154,10.554772,11.732667,10.858331,11.965896,11.519145,11.697593,12.724883,12.771710,12.707346
52439,10.886002,10.178796,12.123380,10.174492,9.945244,9.271161,11.033095,11.865687,12.354125,12.950544,...,11.188423,10.925115,12.144340,11.239325,12.385752,11.923326,12.108034,13.171371,13.219840,13.153218
52440,9.404284,8.718525,10.235227,8.699241,8.406802,7.885032,9.310576,10.047332,10.448939,10.965130,...,9.536878,9.339421,10.309173,9.527953,10.476509,10.092911,10.242558,11.164340,11.220597,11.202747
52441,9.874498,9.154451,10.746988,9.134203,8.827142,8.279284,9.776104,10.549699,10.971386,11.513387,...,10.013722,9.806392,10.824632,10.004351,11.000335,10.597557,10.754685,11.722557,11.781627,11.762885

In [32]:
R = 1/Turbinedata_V

In [33]:
TI_cal_respoint_dir

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
1,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
2,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
3,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
4,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52438,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52439,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52440,0.289489,0.299444,0.237467,0.299911,0.324622,0.328444,0.290533,0.235222,0.228422,0.205778,...,0.262600,0.249111,0.247089,0.258022,0.228289,0.217044,0.242333,0.172067,0.180289,0.191089
52441,0.289489,0.299444,0.237467,0.299911,0.324622,0.328444,0.290533,0.235222,0.228422,0.205778,...,0.262600,0.249111,0.247089,0.258022,0.228289,0.217044,0.242333,0.172067,0.180289,0.191089

In [34]:
Delta_TI_mast_dir

              0
0      0.277444
1      0.221889
2     -0.278111
3     -0.278111
4      0.436175
...         ...
52437 -0.135517
52438 -0.115159
52439 -0.144151
52440 -0.143178
52441 -0.137463

[52442 rows x 1 columns]

In [35]:
R

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,0.911041,1.049439,1.149899,1.044499,1.280900,1.220817,1.224955,1.089201,1.072576,1.057069,...,1.085369,1.036879,1.056539,1.138924,1.078521,1.106543,1.151155,1.011749,0.988735,0.941768
1,2.049842,2.361238,2.587273,2.350124,2.882025,2.746839,2.756150,2.450702,2.413296,2.378405,...,2.442080,2.332978,2.377213,2.562579,2.426671,2.489721,2.590098,2.276436,2.224654,2.118978
2,2.733122,3.148317,3.449697,3.133498,3.842700,3.662452,3.674866,3.267602,3.217728,3.171207,...,3.256107,3.110637,3.169618,3.416772,3.235562,3.319628,3.453464,3.035248,2.966205,2.825305
3,2.733122,3.148317,3.449697,3.133498,3.842700,3.662452,3.674866,3.267602,3.217728,3.171207,...,3.256107,3.110637,3.169618,3.416772,3.235562,3.319628,3.453464,3.035248,2.966205,2.825305
4,1.171338,1.349279,1.478442,1.342928,1.646872,1.569622,1.574943,1.400401,1.379026,1.359089,...,1.395474,1.333130,1.358408,1.464331,1.386669,1.422698,1.480056,1.300820,1.271231,1.210845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.102260,0.109365,0.091823,0.109412,0.111934,0.120072,0.100897,0.093817,0.090108,0.085958,...,0.099496,0.101894,0.091665,0.099046,0.089878,0.093364,0.091940,0.084517,0.084207,0.084634
52438,0.095084,0.101691,0.085379,0.101734,0.104079,0.111646,0.093817,0.087234,0.083785,0.079926,...,0.092514,0.094744,0.085232,0.092095,0.083571,0.086812,0.085488,0.078586,0.078298,0.078695
52439,0.091861,0.098243,0.082485,0.098285,0.100551,0.107861,0.090636,0.084277,0.080945,0.077217,...,0.089378,0.091532,0.082343,0.088973,0.080738,0.083869,0.082590,0.075922,0.075644,0.076027
52440,0.106335,0.114698,0.097702,0.114953,0.118951,0.126823,0.107405,0.099529,0.095704,0.091198,...,0.104856,0.107073,0.097001,0.104954,0.095452,0.099079,0.097632,0.089571,0.089122,0.089264
52441,0.101271,0.109236,0.093049,0.109479,0.113287,0.120783,0.102290,0.094789,0.091146,0.086855,...,0.099863,0.101974,0.092382,0.099957,0.090906,0.094361,0.092983,0.085306,0.084878,0.085013

In [36]:
TI_cal_respoint_1_reset = TI_cal_respoint_1.reset_index(drop=True)
TI_cal_respoint_2_reset = TI_cal_respoint_2.reset_index(drop=True)

TI_cal_respoint_dir = TI_cal_respoint_1_reset.mul(lambda_col_reset1, axis=0) + TI_cal_respoint_2_reset.mul(lambda_col_reset2, axis=0)

In [37]:
TI_cal_respoint_dir

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
1,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
2,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
3,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
4,0.218556,0.273889,0.295111,0.260222,0.334000,0.299778,0.345556,0.271444,0.289889,0.278444,...,0.258333,0.229111,0.271000,0.294111,0.271667,0.273667,0.307000,0.228111,0.214333,0.201444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52438,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52439,0.294911,0.300556,0.233733,0.301289,0.322978,0.329556,0.286267,0.232778,0.224378,0.202222,...,0.263800,0.250889,0.245711,0.255178,0.225311,0.213356,0.239667,0.169533,0.179311,0.191711
52440,0.289489,0.299444,0.237467,0.299911,0.324622,0.328444,0.290533,0.235222,0.228422,0.205778,...,0.262600,0.249111,0.247089,0.258022,0.228289,0.217044,0.242333,0.172067,0.180289,0.191089
52441,0.289489,0.299444,0.237467,0.299911,0.324622,0.328444,0.290533,0.235222,0.228422,0.205778,...,0.262600,0.249111,0.247089,0.258022,0.228289,0.217044,0.242333,0.172067,0.180289,0.191089

In [92]:
TI_cal_mast_dir.squeeze()

0        0.278111
1        0.278111
2        0.278111
3        0.278111
4        0.278111
           ...
52437    0.220422
52438    0.220422
52439    0.220422
52440    0.223178
52441    0.223178
Name: 0, Length: 52442, dtype: float64

In [93]:
Delta_TI_dir = TI_cal_respoint_dir.sub(TI_cal_mast_dir.squeeze(), axis=0)
Delta_TI_dir

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,-0.059556,-0.004222,0.017000,-0.017889,0.055889,0.021667,0.067444,-0.006667,0.011778,0.000333,...,-0.019778,-0.049000,-0.007111,0.016000,-0.006444,-0.004444,0.028889,-0.050000,-0.063778,-0.076667
1,-0.059556,-0.004222,0.017000,-0.017889,0.055889,0.021667,0.067444,-0.006667,0.011778,0.000333,...,-0.019778,-0.049000,-0.007111,0.016000,-0.006444,-0.004444,0.028889,-0.050000,-0.063778,-0.076667
2,-0.059556,-0.004222,0.017000,-0.017889,0.055889,0.021667,0.067444,-0.006667,0.011778,0.000333,...,-0.019778,-0.049000,-0.007111,0.016000,-0.006444,-0.004444,0.028889,-0.050000,-0.063778,-0.076667
3,-0.059556,-0.004222,0.017000,-0.017889,0.055889,0.021667,0.067444,-0.006667,0.011778,0.000333,...,-0.019778,-0.049000,-0.007111,0.016000,-0.006444,-0.004444,0.028889,-0.050000,-0.063778,-0.076667
4,-0.059556,-0.004222,0.017000,-0.017889,0.055889,0.021667,0.067444,-0.006667,0.011778,0.000333,...,-0.019778,-0.049000,-0.007111,0.016000,-0.006444,-0.004444,0.028889,-0.050000,-0.063778,-0.076667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.074489,0.080133,0.013311,0.080867,0.102556,0.109133,0.065844,0.012356,0.003956,-0.018200,...,0.043378,0.030467,0.025289,0.034756,0.004889,-0.007067,0.019244,-0.050889,-0.041111,-0.028711
52438,0.074489,0.080133,0.013311,0.080867,0.102556,0.109133,0.065844,0.012356,0.003956,-0.018200,...,0.043378,0.030467,0.025289,0.034756,0.004889,-0.007067,0.019244,-0.050889,-0.041111,-0.028711
52439,0.074489,0.080133,0.013311,0.080867,0.102556,0.109133,0.065844,0.012356,0.003956,-0.018200,...,0.043378,0.030467,0.025289,0.034756,0.004889,-0.007067,0.019244,-0.050889,-0.041111,-0.028711
52440,0.066311,0.076267,0.014289,0.076733,0.101444,0.105267,0.067356,0.012044,0.005244,-0.017400,...,0.039422,0.025933,0.023911,0.034844,0.005111,-0.006133,0.019156,-0.051111,-0.042889,-0.032089
52441,0.066311,0.076267,0.014289,0.076733,0.101444,0.105267,0.067356,0.012044,0.005244,-0.017400,...,0.039422,0.025933,0.023911,0.034844,0.005111,-0.006133,0.019156,-0.051111,-0.042889,-0.032089

In [39]:
R

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,0.911041,1.049439,1.149899,1.044499,1.280900,1.220817,1.224955,1.089201,1.072576,1.057069,...,1.085369,1.036879,1.056539,1.138924,1.078521,1.106543,1.151155,1.011749,0.988735,0.941768
1,2.049842,2.361238,2.587273,2.350124,2.882025,2.746839,2.756150,2.450702,2.413296,2.378405,...,2.442080,2.332978,2.377213,2.562579,2.426671,2.489721,2.590098,2.276436,2.224654,2.118978
2,2.733122,3.148317,3.449697,3.133498,3.842700,3.662452,3.674866,3.267602,3.217728,3.171207,...,3.256107,3.110637,3.169618,3.416772,3.235562,3.319628,3.453464,3.035248,2.966205,2.825305
3,2.733122,3.148317,3.449697,3.133498,3.842700,3.662452,3.674866,3.267602,3.217728,3.171207,...,3.256107,3.110637,3.169618,3.416772,3.235562,3.319628,3.453464,3.035248,2.966205,2.825305
4,1.171338,1.349279,1.478442,1.342928,1.646872,1.569622,1.574943,1.400401,1.379026,1.359089,...,1.395474,1.333130,1.358408,1.464331,1.386669,1.422698,1.480056,1.300820,1.271231,1.210845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.102260,0.109365,0.091823,0.109412,0.111934,0.120072,0.100897,0.093817,0.090108,0.085958,...,0.099496,0.101894,0.091665,0.099046,0.089878,0.093364,0.091940,0.084517,0.084207,0.084634
52438,0.095084,0.101691,0.085379,0.101734,0.104079,0.111646,0.093817,0.087234,0.083785,0.079926,...,0.092514,0.094744,0.085232,0.092095,0.083571,0.086812,0.085488,0.078586,0.078298,0.078695
52439,0.091861,0.098243,0.082485,0.098285,0.100551,0.107861,0.090636,0.084277,0.080945,0.077217,...,0.089378,0.091532,0.082343,0.088973,0.080738,0.083869,0.082590,0.075922,0.075644,0.076027
52440,0.106335,0.114698,0.097702,0.114953,0.118951,0.126823,0.107405,0.099529,0.095704,0.091198,...,0.104856,0.107073,0.097001,0.104954,0.095452,0.099079,0.097632,0.089571,0.089122,0.089264
52441,0.101271,0.109236,0.093049,0.109479,0.113287,0.120783,0.102290,0.094789,0.091146,0.086855,...,0.099863,0.101974,0.092382,0.099957,0.090906,0.094361,0.092983,0.085306,0.084878,0.085013

In [94]:
R.multiply(Delta_TI_dir)

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,-0.054258,-0.004431,0.019548,-0.018685,0.071588,0.026451,0.082616,-0.007261,0.012633,0.000352,...,-0.021466,-0.050807,-0.007513,0.018223,-0.006950,-0.004918,0.033256,-0.050587,-0.063059,-0.072202
1,-0.122079,-0.009970,0.043984,-0.042041,0.161073,0.059515,0.185887,-0.016338,0.028423,0.000793,...,-0.048299,-0.114316,-0.016905,0.041001,-0.015639,-0.011065,0.074825,-0.113822,-0.141883,-0.162455
2,-0.162773,-0.013293,0.058645,-0.056055,0.214764,0.079353,0.247849,-0.021784,0.037898,0.001057,...,-0.064399,-0.152421,-0.022540,0.054668,-0.020851,-0.014754,0.099767,-0.151762,-0.189178,-0.216607
3,-0.162773,-0.013293,0.058645,-0.056055,0.214764,0.079353,0.247849,-0.021784,0.037898,0.001057,...,-0.064399,-0.152421,-0.022540,0.054668,-0.020851,-0.014754,0.099767,-0.151762,-0.189178,-0.216607
4,-0.069760,-0.005697,0.025134,-0.024023,0.092042,0.034008,0.106221,-0.009336,0.016242,0.000453,...,-0.027599,-0.065323,-0.009660,0.023429,-0.008936,-0.006323,0.042757,-0.065041,-0.081076,-0.092831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.007617,0.008764,0.001222,0.008848,0.011479,0.013104,0.006644,0.001159,0.000356,-0.001564,...,0.004316,0.003104,0.002318,0.003442,0.000439,-0.000660,0.001769,-0.004301,-0.003462,-0.002430
52438,0.007083,0.008149,0.001136,0.008227,0.010674,0.012184,0.006177,0.001078,0.000331,-0.001455,...,0.004013,0.002887,0.002155,0.003201,0.000409,-0.000613,0.001645,-0.003999,-0.003219,-0.002259
52439,0.006843,0.007873,0.001098,0.007948,0.010312,0.011771,0.005968,0.001041,0.000320,-0.001405,...,0.003877,0.002789,0.002082,0.003092,0.000395,-0.000593,0.001589,-0.003864,-0.003110,-0.002183
52440,0.007051,0.008748,0.001396,0.008821,0.012067,0.013350,0.007234,0.001199,0.000502,-0.001587,...,0.004134,0.002777,0.002319,0.003657,0.000488,-0.000608,0.001870,-0.004578,-0.003822,-0.002864
52441,0.006715,0.008331,0.001330,0.008401,0.011492,0.012714,0.006890,0.001142,0.000478,-0.001511,...,0.003937,0.002645,0.002209,0.003483,0.000465,-0.000579,0.001781,-0.004360,-0.003640,-0.002728

In [101]:
TI_mes

0        0.555556
1        0.500000
2        0.000000
3        0.000000
4        0.714286
           ...
52437    0.084906
52438    0.105263
52439    0.076271
52440    0.080000
52441    0.085714
Length: 52442, dtype: float64

In [111]:
TI_co_respoint_dir = R.multiply(Delta_TI_dir).add(TI_mes, axis=0)
TI_co_respoint_dir

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,0.501298,0.551125,0.575104,0.536871,0.627144,0.582007,0.638172,0.548294,0.568188,0.555908,...,0.534089,0.504748,0.548042,0.573778,0.548605,0.550638,0.588811,0.504968,0.492496,0.483353
1,0.377921,0.490030,0.543984,0.457959,0.661073,0.559515,0.685887,0.483662,0.528423,0.500793,...,0.451701,0.385684,0.483095,0.541001,0.484361,0.488935,0.574825,0.386178,0.358117,0.337545
2,-0.162773,-0.013293,0.058645,-0.056055,0.214764,0.079353,0.247849,-0.021784,0.037898,0.001057,...,-0.064399,-0.152421,-0.022540,0.054668,-0.020851,-0.014754,0.099767,-0.151762,-0.189178,-0.216607
3,-0.162773,-0.013293,0.058645,-0.056055,0.214764,0.079353,0.247849,-0.021784,0.037898,0.001057,...,-0.064399,-0.152421,-0.022540,0.054668,-0.020851,-0.014754,0.099767,-0.151762,-0.189178,-0.216607
4,0.644526,0.708589,0.739419,0.690262,0.806328,0.748294,0.820507,0.704950,0.730528,0.714739,...,0.686686,0.648962,0.704626,0.737715,0.705349,0.707963,0.757043,0.649245,0.633209,0.621454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,0.092523,0.093669,0.086128,0.093753,0.096385,0.098010,0.091549,0.086065,0.085262,0.083341,...,0.089222,0.088010,0.087224,0.088348,0.085345,0.084246,0.086675,0.080605,0.081444,0.082476
52438,0.112346,0.113412,0.106400,0.113490,0.115937,0.117447,0.111440,0.106341,0.105595,0.103809,...,0.109276,0.108150,0.107419,0.108464,0.105672,0.104650,0.106908,0.101264,0.102044,0.103004
52439,0.083114,0.084144,0.077369,0.084219,0.086583,0.088042,0.082239,0.077312,0.076591,0.074866,...,0.080148,0.079060,0.078354,0.079364,0.076666,0.075679,0.077861,0.072408,0.073161,0.074088
52440,0.087051,0.088748,0.081396,0.088821,0.092067,0.093350,0.087234,0.081199,0.080502,0.078413,...,0.084134,0.082777,0.082319,0.083657,0.080488,0.079392,0.081870,0.075422,0.076178,0.077136
52441,0.092430,0.094045,0.087044,0.094115,0.097207,0.098429,0.092604,0.086856,0.086192,0.084203,...,0.089651,0.088359,0.087923,0.089197,0.086179,0.085136,0.087495,0.081354,0.082074,0.082986

In [112]:
Turbinedata_V>10

,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52437,False,False,True,False,False,False,False,True,True,True,...,True,False,True,True,True,True,True,True,True,True
52438,True,False,True,False,False,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
52439,True,True,True,True,False,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
52440,False,False,True,False,False,False,False,True,True,True,...,False,False,True,False,True,True,True,True,True,True
52441,False,False,True,False,False,False,False,True,True,True,...,True,False,True,True,True,True,True,True,True,True

In [113]:
TI_co_respoint_dir[Turbinedata_V>10].mean()

1     0.114154
2     0.113401
3     0.113535
4     0.112482
5     0.112191
6     0.110495
7     0.113424
8     0.111558
9     0.112694
10    0.113405
11    0.112346
12    0.112235
13    0.113459
14    0.112731
15    0.114482
16    0.110066
17    0.113518
18    0.112909
19    0.112257
20    0.112514
21    0.113903
22    0.111644
23    0.110603
24    0.111506
dtype: float64